services:
  msm-sis-db:
    image: mysql:8.4
    restart: unless-stopped
    command: --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: msmsisdb
      MYSQL_DATABASE: msmsisdb
    ports:
      - "3307:3306"
    volumes:
      - msm_sis_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pmsmsisdb"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 8s

  msm-sis-frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_PROXY_TARGET: "http://msm-sis-api:8080"

  msm-sis-api:
    build:
      context: ./api
    ports:
      - "8081:8080"
    depends_on:
      msm-sis-db:
        condition: service_healthy
    volumes:
      - ./msm-sis-file-share:/app/files
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://msm-sis-db:3306/msmsisdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: msmsisdb
      APP_STORAGE_ROOT_DIR: /app/files

volumes:
  msm_sis_db_data:
  #Change this to the volume share for msm-sis-api volume later.c
  msm_sis_files:
