CREATE TABLE degree_type (
    degree_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    sort_order INT NOT NULL
);

INSERT INTO degree_type (code, name, sort_order) VALUES
    ('BACHELOR', 'Bachelor', 1),
    ('MASTER', 'Master', 2);

CREATE TABLE program_type (
    program_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    sort_order INT NOT NULL
);

INSERT INTO program_type (code, name, sort_order) VALUES
    ('MAJOR', 'Major', 1),
    ('MINOR', 'Minor', 2),
    ('CORE', 'Core', 3);

CREATE TABLE program (
    program_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NULL,
    department_id BIGINT NULL,
    program_type_id BIGINT NOT NULL,
    degree_type_id BIGINT NULL,

    code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_program_school
        FOREIGN KEY (school_id) REFERENCES academic_school(school_id),

    CONSTRAINT fk_program_department
        FOREIGN KEY (department_id) REFERENCES academic_department(department_id),

    CONSTRAINT fk_program_program_type
        FOREIGN KEY (program_type_id) REFERENCES program_type(program_type_id),

    CONSTRAINT fk_program_degree_type
        FOREIGN KEY (degree_type_id) REFERENCES degree_type(degree_type_id),

    CONSTRAINT uq_program_code
        UNIQUE (code)
);

CREATE TABLE program_version (
    program_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_id BIGINT NOT NULL,

    version_number INT NOT NULL,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    class_year_start INT NOT NULL,
    class_year_end INT NULL,
    notes VARCHAR(500) NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_program_version_program
        FOREIGN KEY (program_id) REFERENCES program(program_id) ON DELETE CASCADE,

    CONSTRAINT uq_program_version_number
        UNIQUE (program_id, version_number),

    CONSTRAINT chk_program_version_number
        CHECK (version_number > 0),

    CONSTRAINT chk_program_version_class_year_start
        CHECK (class_year_start >= 1900),

    CONSTRAINT chk_program_version_class_year_end
        CHECK (class_year_end IS NULL OR class_year_end >= class_year_start)
);

CREATE TABLE requirement (
    requirement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    requirement_type VARCHAR(50) NOT NULL,
    description TEXT NULL,
    minimum_credits DECIMAL(5,2) NULL,
    minimum_courses INT NULL,
    course_match_mode VARCHAR(50) NULL,
    minimum_grade VARCHAR(10) NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_requirement_code
        UNIQUE (code),

    CONSTRAINT chk_requirement_type
        CHECK (
            requirement_type IN (
                'TOTAL_ELECTIVE_CREDITS',
                'SPECIFIC_COURSES',
                'DEPARTMENT_LEVEL_COURSES',
                'MANUAL'
            )
        ),

    CONSTRAINT chk_requirement_minimum_credits
        CHECK (minimum_credits IS NULL OR minimum_credits >= 0),

    CONSTRAINT chk_requirement_minimum_courses
        CHECK (minimum_courses IS NULL OR minimum_courses >= 0),

    CONSTRAINT chk_requirement_course_match_mode
        CHECK (course_match_mode IS NULL OR course_match_mode IN ('ALL', 'ANY'))
);

CREATE TABLE requirement_course (
    requirement_course_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,

    required BOOLEAN NOT NULL DEFAULT TRUE,
    minimum_grade VARCHAR(10) NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_requirement_course_requirement
        FOREIGN KEY (requirement_id) REFERENCES requirement(requirement_id) ON DELETE CASCADE,

    CONSTRAINT fk_requirement_course_course
        FOREIGN KEY (course_id) REFERENCES course(course_id),

    CONSTRAINT uq_requirement_course
        UNIQUE (requirement_id, course_id)
);

CREATE TABLE requirement_course_rule (
    requirement_course_rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,

    minimum_course_number INT NULL,
    maximum_course_number INT NULL,
    minimum_credits DECIMAL(5,2) NULL,
    minimum_courses INT NULL,
    minimum_grade VARCHAR(10) NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_requirement_course_rule_requirement
        FOREIGN KEY (requirement_id) REFERENCES requirement(requirement_id) ON DELETE CASCADE,

    CONSTRAINT fk_requirement_course_rule_department
        FOREIGN KEY (department_id) REFERENCES academic_department(department_id),

    CONSTRAINT chk_requirement_course_rule_course_number
        CHECK (
            minimum_course_number IS NULL
            OR maximum_course_number IS NULL
            OR maximum_course_number >= minimum_course_number
        ),

    CONSTRAINT chk_requirement_course_rule_minimum_credits
        CHECK (minimum_credits IS NULL OR minimum_credits >= 0),

    CONSTRAINT chk_requirement_course_rule_minimum_courses
        CHECK (minimum_courses IS NULL OR minimum_courses >= 0)
);

CREATE TABLE program_version_requirement (
    program_version_requirement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    program_version_id BIGINT NOT NULL,
    requirement_id BIGINT NOT NULL,

    sort_order INT NOT NULL DEFAULT 0,
    required BOOLEAN NOT NULL DEFAULT TRUE,
    notes VARCHAR(500) NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_program_version_requirement_version
        FOREIGN KEY (program_version_id)
            REFERENCES program_version(program_version_id) ON DELETE CASCADE,

    CONSTRAINT fk_program_version_requirement_requirement
        FOREIGN KEY (requirement_id)
            REFERENCES requirement(requirement_id),

    CONSTRAINT uq_program_version_requirement
        UNIQUE (program_version_id, requirement_id),

    CONSTRAINT chk_program_version_requirement_sort_order
        CHECK (sort_order >= 0)
);

CREATE INDEX idx_program_school
    ON program (school_id);

CREATE INDEX idx_program_department
    ON program (department_id);

CREATE INDEX idx_program_program_type
    ON program (program_type_id);

CREATE INDEX idx_program_degree_type
    ON program (degree_type_id);

CREATE INDEX idx_program_version_program
    ON program_version (program_id);

CREATE INDEX idx_program_version_class_year
    ON program_version (program_id, class_year_start, class_year_end);

CREATE UNIQUE INDEX uq_program_version_published_open_ended
    ON program_version (program_id)
    WHERE is_published = TRUE
      AND class_year_end IS NULL;

CREATE INDEX idx_program_version_requirement_version
    ON program_version_requirement (program_version_id);

CREATE INDEX idx_program_version_requirement_requirement
    ON program_version_requirement (requirement_id);

CREATE INDEX idx_requirement_course_requirement
    ON requirement_course (requirement_id);

CREATE INDEX idx_requirement_course_course
    ON requirement_course (course_id);

CREATE INDEX idx_requirement_course_rule_requirement
    ON requirement_course_rule (requirement_id);

CREATE INDEX idx_requirement_course_rule_department
    ON requirement_course_rule (department_id);

CREATE FUNCTION prevent_program_version_class_year_overlap()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.is_published = FALSE THEN
        RETURN NEW;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM program_version existing_version
        WHERE existing_version.program_id = NEW.program_id
          AND existing_version.program_version_id <> COALESCE(NEW.program_version_id, -1)
          AND existing_version.is_published = TRUE
          AND existing_version.class_year_start <= COALESCE(NEW.class_year_end, 2147483647)
          AND NEW.class_year_start <= COALESCE(existing_version.class_year_end, 2147483647)
    ) THEN
        RAISE EXCEPTION 'Published program versions cannot have overlapping class year ranges.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE FUNCTION validate_program_department_school()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.department_id IS NOT NULL
        AND NOT EXISTS (
            SELECT 1
            FROM academic_department department
            WHERE department.department_id = NEW.department_id
              AND department.school_id = NEW.school_id
        )
    THEN
        RAISE EXCEPTION 'Program department must belong to the selected school.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_program_updated_at
    BEFORE UPDATE ON program
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_program_version_updated_at
    BEFORE UPDATE ON program_version
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_requirement_updated_at
    BEFORE UPDATE ON requirement
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_requirement_course_updated_at
    BEFORE UPDATE ON requirement_course
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_requirement_course_rule_updated_at
    BEFORE UPDATE ON requirement_course_rule
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_program_version_requirement_updated_at
    BEFORE UPDATE ON program_version_requirement
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_program_version_class_year_overlap
    BEFORE INSERT OR UPDATE ON program_version
    FOR EACH ROW
    EXECUTE FUNCTION prevent_program_version_class_year_overlap();

CREATE TRIGGER trg_program_department_school
    BEFORE INSERT OR UPDATE ON program
    FOR EACH ROW
    EXECUTE FUNCTION validate_program_department_school();
