CREATE TABLE course_version_requisite_group (
    course_version_requisite_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_version_id BIGINT NOT NULL,

    requisite_type VARCHAR(20) NOT NULL,
    condition_type VARCHAR(20) NOT NULL,
    minimum_required INT,
    sort_order INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_course_version_requisite_group_course_version
        FOREIGN KEY (course_version_id)
            REFERENCES course_version(course_version_id)
            ON DELETE CASCADE,

    CONSTRAINT chk_course_version_requisite_group_requisite_type
        CHECK (requisite_type IN ('PREREQUISITE', 'COREQUISITE')),

    CONSTRAINT chk_course_version_requisite_group_condition_type
        CHECK (condition_type IN ('ALL', 'ANY')),

    CONSTRAINT chk_course_version_requisite_group_minimum_required
        CHECK (
            (condition_type = 'ALL' AND minimum_required IS NULL)
            OR (condition_type = 'ANY' AND minimum_required IS NOT NULL AND minimum_required > 0)
        ),

    CONSTRAINT chk_course_version_requisite_group_sort_order
        CHECK (sort_order >= 0)
);

CREATE TABLE course_version_requisite_course (
    course_version_requisite_course_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_version_requisite_group_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,

    sort_order INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_course_version_requisite_course_group
        FOREIGN KEY (course_version_requisite_group_id)
            REFERENCES course_version_requisite_group(course_version_requisite_group_id)
            ON DELETE CASCADE,

    CONSTRAINT fk_course_version_requisite_course_course
        FOREIGN KEY (course_id)
            REFERENCES course(course_id),

    CONSTRAINT uq_course_version_requisite_course
        UNIQUE (course_version_requisite_group_id, course_id),

    CONSTRAINT chk_course_version_requisite_course_sort_order
        CHECK (sort_order >= 0)
);

CREATE INDEX idx_course_version_requisite_group_course_version
    ON course_version_requisite_group (course_version_id);

CREATE INDEX idx_course_version_requisite_group_type
    ON course_version_requisite_group (requisite_type);

CREATE INDEX idx_course_version_requisite_course_group
    ON course_version_requisite_course (course_version_requisite_group_id);

CREATE INDEX idx_course_version_requisite_course_course
    ON course_version_requisite_course (course_id);

CREATE TRIGGER trg_course_version_requisite_group_updated_at
    BEFORE UPDATE ON course_version_requisite_group
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_course_version_requisite_course_updated_at
    BEFORE UPDATE ON course_version_requisite_course
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
