CREATE TABLE athletic_sport (
    athletic_sport_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    code VARCHAR(30) NOT NULL,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_user_id BIGINT NULL,

    CONSTRAINT fk_athletic_sport_updated_by
        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id),

    CONSTRAINT uq_athletic_sport_code
        UNIQUE (code),

    CONSTRAINT uq_athletic_sport_name
        UNIQUE (name)
);

CREATE TABLE student_honors (
    student_honors_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_user_id BIGINT NULL,

    CONSTRAINT fk_student_honors_student
        FOREIGN KEY (student_id)
            REFERENCES student(student_id) ON DELETE CASCADE,

    CONSTRAINT fk_student_honors_updated_by
        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id),

    CONSTRAINT uq_student_honors_student
        UNIQUE (student_id)
);

CREATE TABLE student_athlete (
    student_athlete_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    athletic_sport_id BIGINT NOT NULL,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by_user_id BIGINT NULL,

    CONSTRAINT fk_student_athlete_student
        FOREIGN KEY (student_id)
            REFERENCES student(student_id) ON DELETE CASCADE,

    CONSTRAINT fk_student_athlete_athletic_sport
        FOREIGN KEY (athletic_sport_id)
            REFERENCES athletic_sport(athletic_sport_id),

    CONSTRAINT fk_student_athlete_updated_by
        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id),

    CONSTRAINT uq_student_athlete_athletic_sport
        UNIQUE (student_id, athletic_sport_id)
);

CREATE INDEX idx_athletic_sport_active
    ON athletic_sport (active);

CREATE INDEX idx_athletic_sport_updated_by
    ON athletic_sport (updated_by_user_id);

CREATE INDEX idx_student_honors_student
    ON student_honors (student_id);

CREATE INDEX idx_student_honors_active
    ON student_honors (active);

CREATE INDEX idx_student_honors_updated_by
    ON student_honors (updated_by_user_id);

CREATE INDEX idx_student_athlete_student
    ON student_athlete (student_id);

CREATE INDEX idx_student_athlete_athletic_sport
    ON student_athlete (athletic_sport_id);

CREATE INDEX idx_student_athlete_active
    ON student_athlete (active);

CREATE INDEX idx_student_athlete_updated_by
    ON student_athlete (updated_by_user_id);

CREATE TRIGGER trg_athletic_sport_updated_at
    BEFORE UPDATE ON athletic_sport
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_student_honors_updated_at
    BEFORE UPDATE ON student_honors
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_student_athlete_updated_at
    BEFORE UPDATE ON student_athlete
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
