CREATE TABLE registration_group_generation (
    registration_group_generation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    academic_year_id BIGINT NOT NULL,
    term_id BIGINT NOT NULL,

    name VARCHAR(255) NOT NULL,

    student_search_text VARCHAR(255) NULL,
    program_search_text VARCHAR(255) NULL,
    group_name_prefix VARCHAR(255) NULL,
    academic_division_id BIGINT NULL,

    honors_filter VARCHAR(30) NOT NULL DEFAULT 'ANY',
    athlete_filter VARCHAR(30) NOT NULL DEFAULT 'ANY',
    existing_group_filter VARCHAR(40) NOT NULL DEFAULT 'EXCLUDE_ALREADY_GROUPED',

    min_credits NUMERIC(5, 2) NULL,
    max_credits NUMERIC(5, 2) NULL,
    include_current_credits BOOLEAN NOT NULL DEFAULT TRUE,
    include_transfer_credits BOOLEAN NOT NULL DEFAULT TRUE,

    split_count INT NOT NULL DEFAULT 1,
    matched_student_count INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id BIGINT NULL,
    updated_by_user_id BIGINT NULL,

    CONSTRAINT fk_registration_group_generation_academic_year
        FOREIGN KEY (academic_year_id)
            REFERENCES academic_year(academic_year_id),

    CONSTRAINT fk_registration_group_generation_term
        FOREIGN KEY (term_id)
            REFERENCES academic_term(term_id),

    CONSTRAINT fk_registration_group_generation_academic_division
        FOREIGN KEY (academic_division_id)
            REFERENCES academic_division(academic_division_id),

    CONSTRAINT fk_registration_group_generation_created_by
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id),

    CONSTRAINT fk_registration_group_generation_updated_by
        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id),

    CONSTRAINT chk_registration_group_generation_honors_filter
        CHECK (honors_filter IN ('ANY', 'HONORS', 'NOT_HONORS')),

    CONSTRAINT chk_registration_group_generation_athlete_filter
        CHECK (athlete_filter IN ('ANY', 'ATHLETE', 'NOT_ATHLETE')),

    CONSTRAINT chk_registration_group_generation_existing_group_filter
        CHECK (existing_group_filter IN ('ANY', 'EXCLUDE_ALREADY_GROUPED', 'ONLY_ALREADY_GROUPED')),

    CONSTRAINT chk_registration_group_generation_credit_range
        CHECK (
            (min_credits IS NULL OR min_credits >= 0)
            AND (max_credits IS NULL OR max_credits >= 0)
            AND (min_credits IS NULL OR max_credits IS NULL OR min_credits <= max_credits)
        ),

    CONSTRAINT chk_registration_group_generation_split_count
        CHECK (split_count > 0),

    CONSTRAINT chk_registration_group_generation_matched_student_count
        CHECK (matched_student_count >= 0)
);

CREATE TABLE registration_group_generation_sport (
    registration_group_generation_sport_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_group_generation_id BIGINT NOT NULL,
    athletic_sport_id BIGINT NOT NULL,

    CONSTRAINT fk_registration_group_generation_sport_generation
        FOREIGN KEY (registration_group_generation_id)
            REFERENCES registration_group_generation(registration_group_generation_id) ON DELETE CASCADE,

    CONSTRAINT fk_registration_group_generation_sport_athletic_sport
        FOREIGN KEY (athletic_sport_id)
            REFERENCES athletic_sport(athletic_sport_id),

    CONSTRAINT uq_registration_group_generation_sport
        UNIQUE (registration_group_generation_id, athletic_sport_id)
);

CREATE TABLE registration_group (
    registration_group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_group_generation_id BIGINT NULL,

    academic_year_id BIGINT NOT NULL,
    term_id BIGINT NOT NULL,

    name VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',

    registration_opens_at TIMESTAMP NULL,
    registration_closes_at TIMESTAMP NULL,
    sort_order INT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id BIGINT NULL,
    updated_by_user_id BIGINT NULL,

    CONSTRAINT fk_registration_group_generation
        FOREIGN KEY (registration_group_generation_id)
            REFERENCES registration_group_generation(registration_group_generation_id) ON DELETE SET NULL,

    CONSTRAINT fk_registration_group_academic_year
        FOREIGN KEY (academic_year_id)
            REFERENCES academic_year(academic_year_id),

    CONSTRAINT fk_registration_group_term
        FOREIGN KEY (term_id)
            REFERENCES academic_term(term_id),

    CONSTRAINT fk_registration_group_created_by
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id),

    CONSTRAINT fk_registration_group_updated_by
        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id),

    CONSTRAINT uq_registration_group_id_year_term
        UNIQUE (registration_group_id, academic_year_id, term_id),

    CONSTRAINT chk_registration_group_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'CLOSED', 'CANCELLED')),

    CONSTRAINT chk_registration_group_window
        CHECK (
            registration_opens_at IS NULL
            OR registration_closes_at IS NULL
            OR registration_opens_at < registration_closes_at
        )
);

CREATE TABLE registration_group_student (
    registration_group_student_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_group_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    academic_year_id BIGINT NOT NULL,
    term_id BIGINT NOT NULL,

    assignment_source VARCHAR(30) NOT NULL DEFAULT 'GENERATED',

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id BIGINT NULL,
    updated_by_user_id BIGINT NULL,

    CONSTRAINT fk_registration_group_student_group
        FOREIGN KEY (registration_group_id, academic_year_id, term_id)
            REFERENCES registration_group(registration_group_id, academic_year_id, term_id) ON DELETE CASCADE,

    CONSTRAINT fk_registration_group_student_student
        FOREIGN KEY (student_id)
            REFERENCES student(student_id) ON DELETE CASCADE,

    CONSTRAINT fk_registration_group_student_created_by
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id),

    CONSTRAINT fk_registration_group_student_updated_by
        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id),

    CONSTRAINT uq_registration_group_student
        UNIQUE (registration_group_id, student_id),

    CONSTRAINT chk_registration_group_student_assignment_source
        CHECK (assignment_source IN ('GENERATED', 'MANUAL'))
);

CREATE TABLE student_course_registration_selection (
    student_course_registration_selection_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    registration_group_id BIGINT NOT NULL,
    selected_grading_basis_id BIGINT NOT NULL,
    selected_credits NUMERIC(4, 2) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id BIGINT NULL,
    updated_by_user_id BIGINT NULL,

    CONSTRAINT fk_student_course_registration_selection_student
        FOREIGN KEY (student_id)
            REFERENCES student(student_id) ON DELETE CASCADE,

    CONSTRAINT fk_student_course_registration_selection_section
        FOREIGN KEY (section_id)
            REFERENCES course_section(section_id) ON DELETE CASCADE,

    CONSTRAINT fk_student_course_registration_selection_group
        FOREIGN KEY (registration_group_id)
            REFERENCES registration_group(registration_group_id) ON DELETE CASCADE,

    CONSTRAINT fk_student_course_registration_selection_grading_basis
        FOREIGN KEY (selected_grading_basis_id)
            REFERENCES grading_basis(grading_basis_id),

    CONSTRAINT fk_student_course_registration_selection_created_by
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id),

    CONSTRAINT fk_student_course_registration_selection_updated_by
        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id),

    CONSTRAINT uq_student_course_registration_selection_student_section
        UNIQUE (student_id, section_id),

    CONSTRAINT uq_student_course_registration_selection_group_section
        UNIQUE (student_id, registration_group_id, section_id),

    CONSTRAINT chk_student_course_registration_selection_credits
        CHECK (selected_credits >= 0)
);

CREATE INDEX idx_registration_group_generation_academic_year_term
    ON registration_group_generation (academic_year_id, term_id);

CREATE INDEX idx_registration_group_generation_academic_division
    ON registration_group_generation (academic_division_id);

CREATE INDEX idx_registration_group_generation_created_by
    ON registration_group_generation (created_by_user_id);

CREATE INDEX idx_registration_group_generation_updated_by
    ON registration_group_generation (updated_by_user_id);

CREATE INDEX idx_registration_group_generation_sport_generation
    ON registration_group_generation_sport (registration_group_generation_id);

CREATE INDEX idx_registration_group_generation_sport_athletic_sport
    ON registration_group_generation_sport (athletic_sport_id);

CREATE INDEX idx_registration_group_generation_sport_lookup
    ON registration_group_generation_sport (athletic_sport_id, registration_group_generation_id);

CREATE INDEX idx_registration_group_generation_text_filters
    ON registration_group_generation (student_search_text, program_search_text);

CREATE INDEX idx_registration_group_generation_filters
    ON registration_group_generation (
        honors_filter,
        athlete_filter,
        existing_group_filter
    );

CREATE INDEX idx_registration_group_generation_credits
    ON registration_group_generation (min_credits, max_credits);

CREATE INDEX idx_registration_group_academic_year_term
    ON registration_group (academic_year_id, term_id);

CREATE INDEX idx_registration_group_generation_id
    ON registration_group (registration_group_generation_id);

CREATE INDEX idx_registration_group_status
    ON registration_group (status);

CREATE INDEX idx_registration_group_created_by
    ON registration_group (created_by_user_id);

CREATE INDEX idx_registration_group_updated_by
    ON registration_group (updated_by_user_id);

CREATE INDEX idx_registration_group_student_group
    ON registration_group_student (registration_group_id);

CREATE INDEX idx_registration_group_student_student
    ON registration_group_student (student_id);

CREATE INDEX idx_registration_group_student_academic_year_term
    ON registration_group_student (academic_year_id, term_id);

CREATE INDEX idx_registration_group_student_created_by
    ON registration_group_student (created_by_user_id);

CREATE INDEX idx_registration_group_student_updated_by
    ON registration_group_student (updated_by_user_id);

CREATE INDEX idx_student_course_registration_selection_student
    ON student_course_registration_selection (student_id);

CREATE INDEX idx_student_course_registration_selection_section
    ON student_course_registration_selection (section_id);

CREATE INDEX idx_student_course_registration_selection_group
    ON student_course_registration_selection (registration_group_id);

CREATE INDEX idx_student_course_registration_selection_grading_basis
    ON student_course_registration_selection (selected_grading_basis_id);

CREATE INDEX idx_student_course_registration_selection_created_by
    ON student_course_registration_selection (created_by_user_id);

CREATE INDEX idx_student_course_registration_selection_updated_by
    ON student_course_registration_selection (updated_by_user_id);

CREATE TRIGGER trg_registration_group_generation_updated_at
    BEFORE UPDATE ON registration_group_generation
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_registration_group_updated_at
    BEFORE UPDATE ON registration_group
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_registration_group_student_updated_at
    BEFORE UPDATE ON registration_group_student
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_student_course_registration_selection_updated_at
    BEFORE UPDATE ON student_course_registration_selection
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
