CREATE TABLE student_section_waitlist_offer (
    student_section_waitlist_offer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_section_enrollment_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,

    status VARCHAR(30) NOT NULL DEFAULT 'OFFERED',
    offered_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    notification_sent_at TIMESTAMP NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_waitlist_offer_enrollment
        FOREIGN KEY (student_section_enrollment_id)
            REFERENCES student_section_enrollment(student_section_enrollment_id),

    CONSTRAINT fk_waitlist_offer_section
        FOREIGN KEY (section_id)
            REFERENCES course_section(section_id),

    CONSTRAINT fk_waitlist_offer_student
        FOREIGN KEY (student_id)
            REFERENCES student(student_id),

    CONSTRAINT chk_waitlist_offer_status
        CHECK (status IN ('OFFERED', 'ACCEPTED', 'EXPIRED', 'CANCELLED')),

    CONSTRAINT chk_waitlist_offer_expires_after_offered
        CHECK (expires_at > offered_at)
);

CREATE INDEX idx_waitlist_offer_enrollment
    ON student_section_waitlist_offer (student_section_enrollment_id);

CREATE INDEX idx_waitlist_offer_section_status_expires
    ON student_section_waitlist_offer (section_id, status, expires_at);

CREATE INDEX idx_waitlist_offer_student_status
    ON student_section_waitlist_offer (student_id, status);

CREATE UNIQUE INDEX uq_waitlist_offer_active_enrollment
    ON student_section_waitlist_offer (student_section_enrollment_id)
    WHERE status = 'OFFERED';

CREATE UNIQUE INDEX uq_waitlist_offer_active_section
    ON student_section_waitlist_offer (section_id)
    WHERE status = 'OFFERED';
