INSERT INTO academic_division (code, name, active, sort_order)
VALUES ('SEMINARY', 'Seminary', TRUE, 3)
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    active = EXCLUDED.active,
    sort_order = EXCLUDED.sort_order;

CREATE TABLE academic_career (
    academic_career_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_academic_career_code
        UNIQUE (code)
);

INSERT INTO academic_career (code, name, active, sort_order)
VALUES
    ('UNDERGRADUATE', 'Undergraduate', TRUE, 1),
    ('GRADUATE', 'Graduate', TRUE, 2),
    ('SEMINARY', 'Seminary', TRUE, 3)
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    active = EXCLUDED.active,
    sort_order = EXCLUDED.sort_order;

CREATE TABLE academic_career_registration_division (
    academic_career_registration_division_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    academic_career_id BIGINT NOT NULL,
    academic_division_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_academic_career_registration_division_career
        FOREIGN KEY (academic_career_id)
            REFERENCES academic_career(academic_career_id) ON DELETE CASCADE,

    CONSTRAINT fk_academic_career_registration_division_division
        FOREIGN KEY (academic_division_id)
            REFERENCES academic_division(academic_division_id) ON DELETE CASCADE,

    CONSTRAINT uq_academic_career_registration_division
        UNIQUE (academic_career_id, academic_division_id)
);

INSERT INTO academic_career_registration_division (academic_career_id, academic_division_id)
SELECT career.academic_career_id, division.academic_division_id
FROM (
    VALUES
        ('UNDERGRADUATE', 'UNDERGRADUATE'),
        ('GRADUATE', 'UNDERGRADUATE'),
        ('GRADUATE', 'GRADUATE'),
        ('SEMINARY', 'UNDERGRADUATE'),
        ('SEMINARY', 'GRADUATE'),
        ('SEMINARY', 'SEMINARY')
) AS allowed(academic_career_code, academic_division_code)
JOIN academic_career career ON career.code = allowed.academic_career_code
JOIN academic_division division ON division.code = allowed.academic_division_code
ON CONFLICT ON CONSTRAINT uq_academic_career_registration_division DO NOTHING;

CREATE TABLE student_academic_career (
    student_academic_career_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    academic_career_id BIGINT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    effective_start_date DATE NOT NULL,
    effective_end_date DATE NULL,
    primary_career BOOLEAN NOT NULL DEFAULT FALSE,
    entry_reason VARCHAR(50) NULL,
    notes VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id BIGINT NULL,
    updated_by_user_id BIGINT NULL,

    CONSTRAINT fk_student_academic_career_student
        FOREIGN KEY (student_id)
            REFERENCES student(student_id) ON DELETE CASCADE,

    CONSTRAINT fk_student_academic_career_career
        FOREIGN KEY (academic_career_id)
            REFERENCES academic_career(academic_career_id),

    CONSTRAINT fk_student_academic_career_created_by
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id),

    CONSTRAINT fk_student_academic_career_updated_by
        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id),

    CONSTRAINT chk_student_academic_career_status
        CHECK (status IN (
            'ACTIVE',
            'INTENT_TO_GRADUATE',
            'GRADUATED',
            'WITHDRAWN',
            'DISMISSED',
            'LEAVE_OF_ABSENCE'
        )),

    CONSTRAINT chk_student_academic_career_dates
        CHECK (effective_end_date IS NULL OR effective_end_date >= effective_start_date)
);

ALTER TABLE student_program
    ADD COLUMN student_academic_career_id BIGINT NULL;

ALTER TABLE student_program
    ADD CONSTRAINT fk_student_program_academic_career
        FOREIGN KEY (student_academic_career_id)
            REFERENCES student_academic_career(student_academic_career_id) ON DELETE SET NULL;

CREATE INDEX idx_academic_career_active_sort
    ON academic_career (active, sort_order);

CREATE INDEX idx_academic_career_registration_division_career
    ON academic_career_registration_division (academic_career_id);

CREATE INDEX idx_academic_career_registration_division_division
    ON academic_career_registration_division (academic_division_id);

CREATE INDEX idx_student_academic_career_student
    ON student_academic_career (student_id);

CREATE INDEX idx_student_academic_career_career
    ON student_academic_career (academic_career_id);

CREATE INDEX idx_student_academic_career_status
    ON student_academic_career (status);

CREATE INDEX idx_student_academic_career_dates
    ON student_academic_career (effective_start_date, effective_end_date);

CREATE INDEX idx_student_academic_career_primary
    ON student_academic_career (primary_career);

CREATE INDEX idx_student_academic_career_created_by
    ON student_academic_career (created_by_user_id);

CREATE INDEX idx_student_academic_career_updated_by
    ON student_academic_career (updated_by_user_id);

CREATE UNIQUE INDEX uq_student_academic_career_student_career
    ON student_academic_career (student_id, academic_career_id)
;

CREATE UNIQUE INDEX uq_student_academic_career_primary_current
    ON student_academic_career (student_id)
    WHERE status = 'ACTIVE' AND effective_end_date IS NULL AND primary_career = TRUE;

CREATE INDEX idx_student_program_academic_career
    ON student_program (student_academic_career_id);

CREATE TRIGGER trg_academic_career_updated_at
    BEFORE UPDATE ON academic_career
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_student_academic_career_updated_at
    BEFORE UPDATE ON student_academic_career
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
