CREATE TABLE transfer_credit_policy (
    transfer_credit_policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    effective_start_date DATE NOT NULL,
    effective_end_date DATE,
    minimum_transfer_grade VARCHAR(10) NOT NULL DEFAULT 'C-',
    four_year_institution_credit_threshold INTEGER NOT NULL DEFAULT 75,
    require_transcript_pdf BOOLEAN NOT NULL DEFAULT TRUE,
    notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_transfer_credit_policy_effective_dates
        CHECK (effective_end_date IS NULL OR effective_end_date >= effective_start_date),
    CONSTRAINT chk_transfer_credit_policy_credit_threshold
        CHECK (four_year_institution_credit_threshold >= 0),
    CONSTRAINT chk_transfer_credit_policy_minimum_grade
        CHECK (minimum_transfer_grade IN ('A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'C-', 'D', 'F'))
);

CREATE INDEX idx_transfer_credit_policy_effective_dates
    ON transfer_credit_policy (effective_start_date, effective_end_date);

CREATE OR REPLACE FUNCTION validate_transfer_credit_policy_date_range()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM transfer_credit_policy existing_policy
        WHERE existing_policy.transfer_credit_policy_id <> COALESCE(NEW.transfer_credit_policy_id, -1)
          AND NEW.effective_start_date <= COALESCE(existing_policy.effective_end_date, DATE '9999-12-31')
          AND COALESCE(NEW.effective_end_date, DATE '9999-12-31') >= existing_policy.effective_start_date
    ) THEN
        RAISE EXCEPTION 'Transfer credit policy effective date range overlaps an existing policy.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_transfer_credit_policy_validate_date_range
    BEFORE INSERT OR UPDATE ON transfer_credit_policy
    FOR EACH ROW
    EXECUTE FUNCTION validate_transfer_credit_policy_date_range();

CREATE TRIGGER trg_transfer_credit_policy_updated_at
    BEFORE UPDATE ON transfer_credit_policy
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

INSERT INTO transfer_credit_policy (
    effective_start_date,
    effective_end_date,
    minimum_transfer_grade,
    four_year_institution_credit_threshold,
    require_transcript_pdf,
    notes
) VALUES (
    DATE '1900-01-01',
    NULL,
    'C-',
    75,
    TRUE,
    'Default transfer credit policy. Student-specific exceptions are tracked as request waivers.'
);
