CREATE TABLE transfer_request (
    transfer_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    transfer_credit_policy_id BIGINT NOT NULL,
    transfer_institution_id BIGINT,
    institution_matched_by_user_id BIGINT,
    institution_matched_at TIMESTAMP,
    one_off_institution_name VARCHAR(255),
    one_off_institution_address_line_1 VARCHAR(255),
    one_off_institution_address_line_2 VARCHAR(255),
    one_off_institution_city VARCHAR(120),
    one_off_institution_state_region VARCHAR(120),
    one_off_institution_postal_code VARCHAR(40),
    one_off_institution_country_code VARCHAR(2),
    one_off_institution_website VARCHAR(255),
    institution_level VARCHAR(20),
    status VARCHAR(40) NOT NULL DEFAULT 'SUBMITTED',
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_by_user_id BIGINT,
    decided_at TIMESTAMP,
    decision_notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_transfer_request_student
        FOREIGN KEY (student_id)
            REFERENCES student(student_id) ON DELETE CASCADE,

    CONSTRAINT fk_transfer_request_policy
        FOREIGN KEY (transfer_credit_policy_id)
            REFERENCES transfer_credit_policy(transfer_credit_policy_id),

    CONSTRAINT fk_transfer_request_institution
        FOREIGN KEY (transfer_institution_id)
            REFERENCES transfer_institution(transfer_institution_id),

    CONSTRAINT fk_transfer_request_institution_matched_by
        FOREIGN KEY (institution_matched_by_user_id)
            REFERENCES users(id),

    CONSTRAINT fk_transfer_request_decided_by
        FOREIGN KEY (decided_by_user_id)
            REFERENCES users(id),

    CONSTRAINT chk_transfer_request_status
        CHECK (status IN (
            'SUBMITTED',
            'WAITING_FOR_MORE_INFO',
            'REGISTRAR_REVIEW',
            'APPROVED',
            'DENIED',
            'CANCELLED'
        )),

    CONSTRAINT chk_transfer_request_decision_required
        CHECK (
            status NOT IN ('APPROVED', 'DENIED')
            OR (decided_by_user_id IS NOT NULL AND decided_at IS NOT NULL)
        ),

    CONSTRAINT chk_transfer_request_decision_pair
        CHECK (
            (decided_by_user_id IS NULL AND decided_at IS NULL)
            OR (decided_by_user_id IS NOT NULL AND decided_at IS NOT NULL)
        ),

    CONSTRAINT chk_transfer_request_institution_level
        CHECK (institution_level IS NULL OR institution_level IN ('TWO_YEAR', 'FOUR_YEAR')),

    CONSTRAINT chk_transfer_request_institution_match_pair
        CHECK (
            (
                transfer_institution_id IS NULL
                AND institution_matched_by_user_id IS NULL
                AND institution_matched_at IS NULL
            )
            OR (
                transfer_institution_id IS NOT NULL
                AND institution_matched_by_user_id IS NOT NULL
                AND institution_matched_at IS NOT NULL
            )
        )
);

CREATE INDEX idx_transfer_request_queue
    ON transfer_request (status, submitted_at, transfer_request_id);

CREATE INDEX idx_transfer_request_student
    ON transfer_request (student_id, submitted_at);

CREATE INDEX idx_transfer_request_institution
    ON transfer_request (transfer_institution_id);

CREATE INDEX idx_transfer_request_institution_matched_by
    ON transfer_request (institution_matched_by_user_id);

CREATE TRIGGER trg_transfer_request_updated_at
    BEFORE UPDATE ON transfer_request
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
