CREATE TABLE transfer_request (
    transfer_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    transfer_credit_policy_id BIGINT NOT NULL,
    status VARCHAR(40) NOT NULL DEFAULT 'SUBMITTED',
    submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_by_user_id BIGINT,
    decided_at TIMESTAMP,
    decision_notes TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_transfer_request_student
        FOREIGN KEY (student_id)
            REFERENCES student(student_id) ON DELETE CASCADE,

    CONSTRAINT fk_transfer_request_policy
        FOREIGN KEY (transfer_credit_policy_id)
            REFERENCES transfer_credit_policy(transfer_credit_policy_id),

    CONSTRAINT fk_transfer_request_decided_by
        FOREIGN KEY (decided_by_user_id)
            REFERENCES users(id),

    CONSTRAINT chk_transfer_request_status
        CHECK (status IN (
            'SUBMITTED',
            'WAITING_FOR_MORE_INFO',
            'REGISTRAR_REVIEW',
            'APPROVED',
            'DENIED',
            'CANCELLED'
        )),

    CONSTRAINT chk_transfer_request_decision_required
        CHECK (
            status NOT IN ('APPROVED', 'DENIED')
            OR (decided_by_user_id IS NOT NULL AND decided_at IS NOT NULL)
        ),

    CONSTRAINT chk_transfer_request_decision_pair
        CHECK (
            (decided_by_user_id IS NULL AND decided_at IS NULL)
            OR (decided_by_user_id IS NOT NULL AND decided_at IS NOT NULL)
        )
);

CREATE INDEX idx_transfer_request_queue
    ON transfer_request (status, submitted_at, transfer_request_id);

CREATE INDEX idx_transfer_request_student
    ON transfer_request (student_id, submitted_at);

CREATE TRIGGER trg_transfer_request_updated_at
    BEFORE UPDATE ON transfer_request
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
