CREATE TABLE transfer_request_attachment (
    transfer_request_attachment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_request_id BIGINT NOT NULL,
    pdf_document_id BIGINT NOT NULL,
    storage_key VARCHAR(255) NOT NULL,
    attachment_type VARCHAR(40) NOT NULL,
    uploaded_by_user_id BIGINT NOT NULL,
    uploaded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_transfer_request_attachment_request
        FOREIGN KEY (transfer_request_id)
            REFERENCES transfer_request(transfer_request_id) ON DELETE CASCADE,

    CONSTRAINT fk_transfer_request_attachment_pdf_document
        FOREIGN KEY (pdf_document_id)
            REFERENCES pdf_documents(id),

    CONSTRAINT fk_transfer_request_attachment_uploaded_by
        FOREIGN KEY (uploaded_by_user_id)
            REFERENCES users(id),

    CONSTRAINT chk_transfer_request_attachment_type
        CHECK (attachment_type IN ('TRANSCRIPT')),

    CONSTRAINT uq_transfer_request_attachment_type
        UNIQUE (transfer_request_id, attachment_type)
);

CREATE INDEX idx_transfer_request_attachment_pdf_document
    ON transfer_request_attachment (pdf_document_id);

CREATE TRIGGER trg_transfer_request_attachment_updated_at
    BEFORE UPDATE ON transfer_request_attachment
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
