CREATE TABLE transfer_request_outcome (
    transfer_request_outcome_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_request_course_id BIGINT NOT NULL,
    outcome_type VARCHAR(40) NOT NULL,
    local_course_id BIGINT,
    requirement_id BIGINT,
    program_version_requirement_id BIGINT,
    accepted_credits DECIMAL(5,2),
    notes TEXT,
    approved_by_user_id BIGINT NOT NULL,
    approved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_transfer_request_outcome_course
        FOREIGN KEY (transfer_request_course_id)
            REFERENCES transfer_request_course(transfer_request_course_id) ON DELETE CASCADE,

    CONSTRAINT fk_transfer_request_outcome_local_course
        FOREIGN KEY (local_course_id)
            REFERENCES course(course_id),

    CONSTRAINT fk_transfer_request_outcome_requirement
        FOREIGN KEY (requirement_id)
            REFERENCES requirement(requirement_id),

    CONSTRAINT fk_transfer_request_outcome_program_version_requirement
        FOREIGN KEY (program_version_requirement_id)
            REFERENCES program_version_requirement(program_version_requirement_id),

    CONSTRAINT fk_transfer_request_outcome_approved_by
        FOREIGN KEY (approved_by_user_id)
            REFERENCES users(id),

    CONSTRAINT chk_transfer_request_outcome_type
        CHECK (outcome_type IN ('TRANSFER_CREDIT', 'COURSE_SUBSTITUTION', 'REQUIREMENT_WAIVER')),

    CONSTRAINT chk_transfer_request_outcome_accepted_credits
        CHECK (accepted_credits IS NULL OR accepted_credits >= 0),

    CONSTRAINT chk_transfer_request_outcome_substitution_target
        CHECK (outcome_type <> 'COURSE_SUBSTITUTION' OR local_course_id IS NOT NULL),

    CONSTRAINT chk_transfer_request_outcome_waiver_target
        CHECK (
            outcome_type <> 'REQUIREMENT_WAIVER'
            OR requirement_id IS NOT NULL
            OR program_version_requirement_id IS NOT NULL
        )
);

CREATE INDEX idx_transfer_request_outcome_course
    ON transfer_request_outcome (transfer_request_course_id, transfer_request_outcome_id);

CREATE INDEX idx_transfer_request_outcome_local_course
    ON transfer_request_outcome (local_course_id);

CREATE INDEX idx_transfer_request_outcome_requirement
    ON transfer_request_outcome (requirement_id);

CREATE INDEX idx_transfer_request_outcome_program_version_requirement
    ON transfer_request_outcome (program_version_requirement_id);

CREATE TRIGGER trg_transfer_request_outcome_updated_at
    BEFORE UPDATE ON transfer_request_outcome
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
