CREATE TABLE transfer_request_policy_waiver (
    transfer_request_policy_waiver_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_request_id BIGINT NOT NULL,
    policy_check_type VARCHAR(50) NOT NULL,
    waived_by_user_id BIGINT NOT NULL,
    waived_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reason TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_transfer_request_policy_waiver_request
        FOREIGN KEY (transfer_request_id)
            REFERENCES transfer_request(transfer_request_id) ON DELETE CASCADE,

    CONSTRAINT fk_transfer_request_policy_waiver_waived_by
        FOREIGN KEY (waived_by_user_id)
            REFERENCES users(id),

    CONSTRAINT chk_transfer_request_policy_waiver_check_type
        CHECK (policy_check_type IN ('MINIMUM_GRADE', 'FOUR_YEAR_INSTITUTION_RULE')),

    CONSTRAINT uq_transfer_request_policy_waiver_check_type
        UNIQUE (transfer_request_id, policy_check_type)
);

CREATE INDEX idx_transfer_request_policy_waiver_request
    ON transfer_request_policy_waiver (transfer_request_id, policy_check_type);

CREATE TRIGGER trg_transfer_request_policy_waiver_updated_at
    BEFORE UPDATE ON transfer_request_policy_waiver
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
