ALTER TABLE transfer_course_equivalency
    ADD COLUMN external_course_description TEXT,
    ADD COLUMN external_credits DECIMAL(5,2),
    ADD COLUMN created_by_user_id BIGINT,
    ADD COLUMN updated_by_user_id BIGINT;

ALTER TABLE transfer_course_equivalency
    ADD CONSTRAINT fk_transfer_course_equivalency_created_by
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id);

ALTER TABLE transfer_course_equivalency
    ADD CONSTRAINT fk_transfer_course_equivalency_updated_by
        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id);

ALTER TABLE transfer_course_equivalency
    ADD CONSTRAINT chk_transfer_course_equivalency_external_credits
        CHECK (external_credits IS NULL OR external_credits >= 0);

CREATE TABLE transfer_course_equivalency_outcome (
    transfer_course_equivalency_outcome_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transfer_course_equivalency_id BIGINT NOT NULL,
    outcome_type VARCHAR(40) NOT NULL,
    local_course_id BIGINT,
    requirement_id BIGINT,
    program_version_requirement_id BIGINT,
    accepted_credits DECIMAL(5,2),
    notes TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_transfer_course_equivalency_outcome_equivalency
        FOREIGN KEY (transfer_course_equivalency_id)
            REFERENCES transfer_course_equivalency(transfer_course_equivalency_id) ON DELETE CASCADE,

    CONSTRAINT fk_transfer_course_equivalency_outcome_local_course
        FOREIGN KEY (local_course_id)
            REFERENCES course(course_id),

    CONSTRAINT fk_transfer_course_equivalency_outcome_requirement
        FOREIGN KEY (requirement_id)
            REFERENCES requirement(requirement_id),

    CONSTRAINT fk_transfer_course_equivalency_outcome_program_version_requirement
        FOREIGN KEY (program_version_requirement_id)
            REFERENCES program_version_requirement(program_version_requirement_id),

    CONSTRAINT chk_transfer_course_equivalency_outcome_type
        CHECK (outcome_type IN ('TRANSFER_CREDIT', 'COURSE_SUBSTITUTION', 'REQUIREMENT_WAIVER')),

    CONSTRAINT chk_transfer_course_equivalency_outcome_accepted_credits
        CHECK (accepted_credits IS NULL OR accepted_credits >= 0),

    CONSTRAINT chk_transfer_course_equivalency_outcome_substitution_target
        CHECK (outcome_type <> 'COURSE_SUBSTITUTION' OR local_course_id IS NOT NULL),

    CONSTRAINT chk_transfer_course_equivalency_outcome_waiver_target
        CHECK (
            outcome_type <> 'REQUIREMENT_WAIVER'
            OR requirement_id IS NOT NULL
            OR program_version_requirement_id IS NOT NULL
        )
);

CREATE INDEX idx_transfer_course_equivalency_created_by
    ON transfer_course_equivalency (created_by_user_id);

CREATE INDEX idx_transfer_course_equivalency_updated_by
    ON transfer_course_equivalency (updated_by_user_id);

CREATE INDEX idx_transfer_course_equivalency_outcome_equivalency
    ON transfer_course_equivalency_outcome (transfer_course_equivalency_id, sort_order);

CREATE INDEX idx_transfer_course_equivalency_outcome_local_course
    ON transfer_course_equivalency_outcome (local_course_id);

CREATE INDEX idx_transfer_course_equivalency_outcome_requirement
    ON transfer_course_equivalency_outcome (requirement_id);

CREATE INDEX idx_transfer_course_equivalency_outcome_program_version_requirement
    ON transfer_course_equivalency_outcome (program_version_requirement_id);

CREATE TRIGGER trg_transfer_course_equivalency_outcome_updated_at
    BEFORE UPDATE ON transfer_course_equivalency_outcome
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
