CREATE TABLE tuition_code (
    tuition_code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id BIGINT NULL,
    updated_by_user_id BIGINT NULL,

    CONSTRAINT uq_tuition_code_code
        UNIQUE (code),

    CONSTRAINT chk_tuition_code_code_not_blank
        CHECK (LENGTH(TRIM(code)) > 0),

    CONSTRAINT chk_tuition_code_name_not_blank
        CHECK (LENGTH(TRIM(name)) > 0),

    CONSTRAINT chk_tuition_code_code_format
        CHECK (code ~ '^[A-Z0-9_]+$'),

    CONSTRAINT fk_tuition_code_created_by
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id),

    CONSTRAINT fk_tuition_code_updated_by
        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id)
);

CREATE TABLE student_tuition_code_assignment (
    student_tuition_code_assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    tuition_code_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id BIGINT NULL,
    updated_by_user_id BIGINT NULL,

    CONSTRAINT uq_student_tuition_code_assignment_student
        UNIQUE (student_id),

    CONSTRAINT fk_student_tuition_code_assignment_student
        FOREIGN KEY (student_id)
            REFERENCES student(student_id) ON DELETE CASCADE,

    CONSTRAINT fk_student_tuition_code_assignment_tuition_code
        FOREIGN KEY (tuition_code_id)
            REFERENCES tuition_code(tuition_code_id),

    CONSTRAINT fk_student_tuition_code_assignment_created_by
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id),

    CONSTRAINT fk_student_tuition_code_assignment_updated_by
        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id)
);

CREATE INDEX idx_tuition_code_created_by
    ON tuition_code (created_by_user_id);

CREATE INDEX idx_tuition_code_updated_by
    ON tuition_code (updated_by_user_id);

CREATE INDEX idx_student_tuition_code_assignment_tuition_code
    ON student_tuition_code_assignment (tuition_code_id);

CREATE INDEX idx_student_tuition_code_assignment_created_by
    ON student_tuition_code_assignment (created_by_user_id);

CREATE INDEX idx_student_tuition_code_assignment_updated_by
    ON student_tuition_code_assignment (updated_by_user_id);

CREATE TRIGGER trg_tuition_code_updated_at
    BEFORE UPDATE ON tuition_code
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_student_tuition_code_assignment_updated_at
    BEFORE UPDATE ON student_tuition_code_assignment
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
