CREATE TABLE ethnicity (
    ethnicity_id INT GENERATED BY DEFAULT AS IDENTITY,
    ethnicity_name VARCHAR(100) NOT NULL,
    PRIMARY KEY (ethnicity_id),
    CONSTRAINT uk_ethnicity_name UNIQUE (ethnicity_name)
);

CREATE TABLE class_standing (
    class_standing_id INT GENERATED BY DEFAULT AS IDENTITY,
    class_standing_name VARCHAR(100) NOT NULL,
    PRIMARY KEY (class_standing_id),
    CONSTRAINT uk_class_standing_name UNIQUE (class_standing_name)
);

CREATE TABLE gender (
    gender_id INT GENERATED BY DEFAULT AS IDENTITY,
    gender_name VARCHAR(100) NOT NULL,
    PRIMARY KEY (gender_id),
    CONSTRAINT uk_gender_name UNIQUE (gender_name)
);

CREATE TABLE address (
    address_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    address_line_1 VARCHAR(255) NOT NULL,
    address_line_2 VARCHAR(255) DEFAULT NULL,
    city VARCHAR(100) NOT NULL,
    state_region VARCHAR(100) DEFAULT NULL,
    postal_code VARCHAR(20) DEFAULT NULL,
    country_code VARCHAR(2) DEFAULT NULL,
    address_lookup_hash VARCHAR(64) DEFAULT NULL,
    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (address_id)
);

CREATE INDEX idx_address_city_state ON address (city, state_region);
CREATE INDEX idx_address_postal_code ON address (postal_code);
CREATE INDEX idx_address_lookup_hash ON address (address_lookup_hash);

CREATE TRIGGER trg_address_last_updated
BEFORE UPDATE ON address
FOR EACH ROW
EXECUTE FUNCTION set_last_updated_timestamp();
