CREATE TABLE billing_period (
    billing_period_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    description VARCHAR(255) NOT NULL,
    type VARCHAR(32) NOT NULL DEFAULT 'STANDARD',
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    academic_year_id BIGINT NULL,
    term_id BIGINT NULL,
    start_date DATE NULL,
    end_date DATE NULL,
    actual_start_preliminary_end_date DATE NULL,
    tax_academic_year VARCHAR(32) NULL,
    tax_academic_year_label VARCHAR(64) NULL,
    tax_academic_term_code VARCHAR(32) NULL,
    tax_academic_term_name VARCHAR(128) NULL,
    financial_aid_period_code VARCHAR(64) NULL,
    financial_aid_period_name VARCHAR(128) NULL,
    course_billing_basis VARCHAR(64) NOT NULL DEFAULT 'BILLING_PERIOD_START_DATE',
    non_course_billing_basis VARCHAR(64) NOT NULL DEFAULT 'BILLING_PERIOD_START_DATE',
    actual_from_to_days INTEGER NOT NULL DEFAULT 0,
    preliminary_from_to_days INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    allow_re_billing BOOLEAN NOT NULL DEFAULT FALSE,
    allow_ar_billing BOOLEAN NOT NULL DEFAULT TRUE,
    include_in_ar_statements BOOLEAN NOT NULL DEFAULT FALSE,
    allow_billing_in_campus_portal BOOLEAN NOT NULL DEFAULT FALSE,
    run_prelim_in_campus_portal_only BOOLEAN NOT NULL DEFAULT FALSE,
    academic_records_mapped BOOLEAN NOT NULL DEFAULT FALSE,
    children_assigned BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id BIGINT NULL,
    updated_by_user_id BIGINT NULL,

    CONSTRAINT uq_billing_period_name
        UNIQUE (name),

    CONSTRAINT chk_billing_period_name_not_blank
        CHECK (LENGTH(TRIM(name)) > 0),

    CONSTRAINT chk_billing_period_description_not_blank
        CHECK (LENGTH(TRIM(description)) > 0),

    CONSTRAINT chk_billing_period_type
        CHECK (type IN ('STANDARD', 'OPEN_ENDED')),

    CONSTRAINT chk_billing_period_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),

    CONSTRAINT chk_billing_period_course_billing_basis
        CHECK (course_billing_basis IN (
            'BILLING_PERIOD_START_DATE',
            'BILLING_PERIOD_END_DATE',
            'ACTUAL_START_PRELIMINARY_END_DATE'
        )),

    CONSTRAINT chk_billing_period_non_course_billing_basis
        CHECK (non_course_billing_basis IN (
            'BILLING_PERIOD_START_DATE',
            'BILLING_PERIOD_END_DATE',
            'ACTUAL_START_PRELIMINARY_END_DATE'
        )),

    CONSTRAINT chk_billing_period_date_range
        CHECK (start_date IS NULL OR end_date IS NULL OR start_date <= end_date),

    CONSTRAINT fk_billing_period_academic_year
        FOREIGN KEY (academic_year_id)
            REFERENCES academic_year(academic_year_id),

    CONSTRAINT fk_billing_period_term
        FOREIGN KEY (term_id)
            REFERENCES academic_term(term_id),

    CONSTRAINT fk_billing_period_created_by
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id),

    CONSTRAINT fk_billing_period_updated_by
        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id)
);

CREATE TABLE billing_period_run (
    billing_period_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    billing_period_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'QUEUED',
    billing_period_status_at_run VARCHAR(32) NOT NULL,
    started_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    trigger_source VARCHAR(32) NOT NULL DEFAULT 'USER',
    triggered_by_user_id BIGINT NULL,
    message TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by_user_id BIGINT NULL,
    updated_by_user_id BIGINT NULL,

    CONSTRAINT chk_billing_period_run_status
        CHECK (status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED')),

    CONSTRAINT chk_billing_period_run_period_status_at_run
        CHECK (billing_period_status_at_run IN ('DRAFT', 'PUBLISHED', 'ARCHIVED')),

    CONSTRAINT chk_billing_period_run_completed_after_started
        CHECK (started_at IS NULL OR completed_at IS NULL OR started_at <= completed_at),

    CONSTRAINT chk_billing_period_run_trigger_source
        CHECK (trigger_source IN ('USER', 'SYSTEM')),

    CONSTRAINT chk_billing_period_run_triggered_by_user
        CHECK (
            (trigger_source = 'USER' AND triggered_by_user_id IS NOT NULL)
            OR
            (trigger_source = 'SYSTEM' AND triggered_by_user_id IS NULL)
        ),

    CONSTRAINT fk_billing_period_run_billing_period
        FOREIGN KEY (billing_period_id)
            REFERENCES billing_period(billing_period_id),

    CONSTRAINT fk_billing_period_run_triggered_by_user
        FOREIGN KEY (triggered_by_user_id)
            REFERENCES users(id),

    CONSTRAINT fk_billing_period_run_created_by
        FOREIGN KEY (created_by_user_id)
            REFERENCES users(id),

    CONSTRAINT fk_billing_period_run_updated_by
        FOREIGN KEY (updated_by_user_id)
            REFERENCES users(id)
);

CREATE INDEX idx_billing_period_academic_year_term
    ON billing_period (academic_year_id, term_id);

CREATE INDEX idx_billing_period_status
    ON billing_period (status);

CREATE INDEX idx_billing_period_created_by
    ON billing_period (created_by_user_id);

CREATE INDEX idx_billing_period_updated_by
    ON billing_period (updated_by_user_id);

CREATE INDEX idx_billing_period_run_billing_period
    ON billing_period_run (billing_period_id);

CREATE INDEX idx_billing_period_run_status
    ON billing_period_run (status);

CREATE INDEX idx_billing_period_run_period_status_at_run
    ON billing_period_run (billing_period_status_at_run);

CREATE INDEX idx_billing_period_run_triggered_by_user
    ON billing_period_run (triggered_by_user_id);

CREATE INDEX idx_billing_period_run_created_by
    ON billing_period_run (created_by_user_id);

CREATE INDEX idx_billing_period_run_updated_by
    ON billing_period_run (updated_by_user_id);

CREATE TRIGGER trg_billing_period_updated_at
    BEFORE UPDATE ON billing_period
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_billing_period_run_updated_at
    BEFORE UPDATE ON billing_period_run
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
