CREATE TABLE student (
 student_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
 user_id BIGINT NULL,

 last_name VARCHAR(50) NOT NULL,
 first_name VARCHAR(50) NOT NULL,
 middle_name VARCHAR(50) DEFAULT NULL,
 name_suffix VARCHAR(10) DEFAULT NULL,

 gender_id INT DEFAULT NULL,
 ethnicity_id INT DEFAULT NULL,
 class_standing_id INT DEFAULT NULL,
 address_id BIGINT DEFAULT NULL,
 preferred_name VARCHAR(255) DEFAULT NULL,

-- SSN (secure design)
 ssn_encrypted BYTEA,
 ssn_lookup_hash VARCHAR(64) DEFAULT NULL,

 date_of_birth DATE DEFAULT NULL,
 estimated_grad_date DATE DEFAULT NULL,

 alt_id VARCHAR(50) DEFAULT NULL,
 email VARCHAR(255) DEFAULT NULL,
 phone VARCHAR(30) DEFAULT NULL,

 is_disabled BOOLEAN NOT NULL DEFAULT FALSE,

 last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_by VARCHAR(255) DEFAULT NULL,

 PRIMARY KEY (student_id),
 CONSTRAINT uk_student_user_id UNIQUE (user_id),
 CONSTRAINT fk_students_user
     FOREIGN KEY (user_id) REFERENCES users(id)
         ON DELETE SET NULL,
 CONSTRAINT fk_student_ethnicity
     FOREIGN KEY (ethnicity_id) REFERENCES ethnicity(ethnicity_id)
         ON DELETE SET NULL,
 CONSTRAINT fk_student_gender
     FOREIGN KEY (gender_id) REFERENCES gender(gender_id)
         ON DELETE SET NULL,
 CONSTRAINT fk_student_class_standing
     FOREIGN KEY (class_standing_id) REFERENCES class_standing(class_standing_id)
         ON DELETE SET NULL,
 CONSTRAINT fk_student_address
     FOREIGN KEY (address_id) REFERENCES address(address_id)
         ON DELETE SET NULL,
 CONSTRAINT uk_student_ssn_lookup_hash UNIQUE (ssn_lookup_hash)
);

CREATE INDEX idx_student_ethnicity ON student (ethnicity_id);
CREATE INDEX idx_student_gender ON student (gender_id);
CREATE INDEX idx_student_class_standing ON student (class_standing_id);
CREATE INDEX idx_student_address ON student (address_id);
CREATE INDEX idx_student_name ON student (last_name, first_name, middle_name);
CREATE INDEX idx_students_active_name ON student (is_disabled, last_name);

CREATE TRIGGER trg_student_last_updated
BEFORE UPDATE ON student
FOR EACH ROW
EXECUTE FUNCTION set_last_updated_timestamp();

CREATE TABLE staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_staff_user_id UNIQUE (user_id),
    CONSTRAINT fk_staff_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE SET NULL
);
