CREATE TABLE academic_school (
    school_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE academic_department (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    code VARCHAR(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_academic_department_school
        FOREIGN KEY (school_id) REFERENCES academic_school(school_id),

    CONSTRAINT uq_academic_department_school_code
        UNIQUE (school_id, code)
);

CREATE TABLE academic_year_status (
    year_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT NOT NULL,
    allow_linear_shift BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE academic_sub_term_status (
    sub_term_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT NOT NULL,
    allow_linear_shift BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE academic_division (
    academic_division_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INT NOT NULL
);

INSERT INTO academic_year_status (code, name, sort_order, allow_linear_shift) VALUES
    ('DRAFT', 'Draft', 1, TRUE),
    ('PLANNED', 'Planned', 2, TRUE),
    ('OPEN', 'Open', 3, TRUE),
    ('ACTIVE', 'Active', 4, TRUE),
    ('CLOSED', 'Closed', 5, TRUE),
    ('CANCELLED', 'Cancelled', 6, FALSE);

INSERT INTO academic_sub_term_status (code, name, sort_order, allow_linear_shift) VALUES
    ('DRAFT', 'Draft', 1, TRUE),
    ('PLANNED', 'Planned', 2, TRUE),
    ('OPEN_FOR_DISPLAY', 'Open for display', 3, TRUE),
    ('OPEN_FOR_REGISTRATION', 'Open for registration', 4, TRUE),
    ('REGISTRATION_CLOSED', 'Registration closed', 5, TRUE),
    ('ACTIVE', 'Active', 6, TRUE),
    ('COMPLETED', 'Completed', 7, TRUE),
    ('CANCELLED', 'Cancelled', 8, FALSE);

INSERT INTO academic_division (code, name, sort_order) VALUES
    ('UNDERGRADUATE', 'Undergraduate', 1),
    ('GRADUATE', 'Graduate', 2);

CREATE TABLE academic_year (
    academic_year_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,

    start_date DATE NOT NULL,
    end_date DATE NOT NULL,

    active BOOLEAN NOT NULL DEFAULT FALSE,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,

    year_status_id BIGINT NOT NULL,

    last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(255) DEFAULT NULL,


    CONSTRAINT chk_academic_year_date_range
       CHECK (start_date <= end_date)
);

CREATE TABLE academic_subject (
    subject_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_academic_subject_department
        FOREIGN KEY (department_id) REFERENCES academic_department(department_id)
);

CREATE TABLE course (
    course_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    course_number VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_course_subject
        FOREIGN KEY (subject_id) REFERENCES academic_subject (subject_id),

    CONSTRAINT uq_course_subject_number
        UNIQUE (subject_id, course_number)
);

CREATE TABLE course_version (
    course_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,

    version_number INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    catalog_description TEXT NULL,

    min_credits DECIMAL(4,2) NOT NULL,
    max_credits DECIMAL(4,2) NOT NULL,
    is_variable_credit BOOLEAN NOT NULL DEFAULT FALSE,

    is_current BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_course_version_course
        FOREIGN KEY (course_id) REFERENCES course(course_id),

    CONSTRAINT uq_course_version_course_version
        UNIQUE (course_id, version_number),

    CONSTRAINT chk_course_version_variable_credit
        CHECK (
            (is_variable_credit = TRUE AND min_credits <= max_credits)
            OR
            (is_variable_credit = FALSE AND min_credits = max_credits)
        )
);

CREATE TABLE academic_sub_term (
   sub_term_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

   academic_year_id BIGINT NOT NULL,

   code VARCHAR(20) NOT NULL,
   name VARCHAR(100) NOT NULL,

   start_date DATE NOT NULL,
   end_date DATE NOT NULL,

   sort_order INT NOT NULL,

   sub_term_status_id BIGINT NOT NULL,
   active BOOLEAN NOT NULL DEFAULT TRUE,

   last_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_by VARCHAR(255) DEFAULT NULL,

   CONSTRAINT fk_academic_sub_term_academic_year
       FOREIGN KEY (academic_year_id) REFERENCES academic_year(academic_year_id),

   CONSTRAINT fk_academic_sub_term_status
       FOREIGN KEY (sub_term_status_id) REFERENCES academic_sub_term_status(sub_term_status_id),

   CONSTRAINT uq_academic_sub_term_year_code
       UNIQUE (academic_year_id, code),

   CONSTRAINT uq_academic_sub_term_year_sort_order
       UNIQUE (academic_year_id, sort_order),

   CONSTRAINT uq_academic_sub_term_id_year
       UNIQUE (sub_term_id, academic_year_id),

   CONSTRAINT chk_academic_sub_term_date_range
       CHECK (start_date <= end_date)
);

CREATE TABLE academic_term (
    term_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    academic_year_id BIGINT NOT NULL,

    code VARCHAR(20) NOT NULL,
    name VARCHAR(100) NOT NULL,

    start_date DATE NOT NULL,
    end_date DATE NOT NULL,

    CONSTRAINT fk_academic_term_academic_year
        FOREIGN KEY (academic_year_id) REFERENCES academic_year(academic_year_id),

    CONSTRAINT uq_academic_term_year_code
        UNIQUE (academic_year_id, code),

    CONSTRAINT chk_academic_term_date_range
        CHECK (start_date <= end_date)
);

CREATE TABLE academic_term_sub_term (
    term_id BIGINT NOT NULL,
    sub_term_id BIGINT NOT NULL,

    PRIMARY KEY (term_id, sub_term_id),

    CONSTRAINT uq_academic_term_sub_term_sub_term
        UNIQUE (sub_term_id),

    CONSTRAINT fk_academic_term_sub_term_term
        FOREIGN KEY (term_id) REFERENCES academic_term(term_id),

    CONSTRAINT fk_academic_term_sub_term_sub_term
        FOREIGN KEY (sub_term_id) REFERENCES academic_sub_term(sub_term_id)
);

CREATE TABLE course_offering (
    course_offering_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    course_version_id BIGINT NOT NULL,
    academic_year_id BIGINT NOT NULL,

    notes VARCHAR(500) NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_course_offering_course_version
        FOREIGN KEY (course_version_id)
            REFERENCES course_version(course_version_id),

    CONSTRAINT fk_course_offering_academic_year
        FOREIGN KEY (academic_year_id) REFERENCES academic_year(academic_year_id),

    CONSTRAINT uq_course_offering_version_year
        UNIQUE (course_version_id, academic_year_id),

    CONSTRAINT uq_course_offering_id_year
        UNIQUE (course_offering_id, academic_year_id)
);

CREATE TABLE course_offering_sub_term (
    course_offering_id BIGINT NOT NULL,
    sub_term_id BIGINT NOT NULL,
    academic_year_id BIGINT NOT NULL,

    PRIMARY KEY (course_offering_id, sub_term_id),

    CONSTRAINT fk_course_offering_sub_term_offering
        FOREIGN KEY (course_offering_id, academic_year_id)
            REFERENCES course_offering(course_offering_id, academic_year_id),

    CONSTRAINT fk_course_offering_sub_term_sub_term
        FOREIGN KEY (sub_term_id, academic_year_id)
            REFERENCES academic_sub_term(sub_term_id, academic_year_id)
);

CREATE UNIQUE INDEX uq_course_version_current_course
    ON course_version (course_id)
    WHERE is_current = TRUE;

CREATE TRIGGER trg_academic_year_last_updated
BEFORE UPDATE ON academic_year
FOR EACH ROW
EXECUTE FUNCTION set_last_updated_timestamp();

CREATE TRIGGER trg_course_updated_at
BEFORE UPDATE ON course
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_course_version_updated_at
BEFORE UPDATE ON course_version
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_academic_sub_term_last_updated
BEFORE UPDATE ON academic_sub_term
FOR EACH ROW
EXECUTE FUNCTION set_last_updated_timestamp();

CREATE TRIGGER trg_course_offering_updated_at
BEFORE UPDATE ON course_offering
FOR EACH ROW
EXECUTE FUNCTION set_updated_at_timestamp();
