CREATE TABLE course_section (
    section_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_offering_id BIGINT NOT NULL,
    sub_term_id BIGINT NOT NULL,
    academic_division_id BIGINT NULL,

    section_letter VARCHAR(5) NOT NULL,
    title VARCHAR(255) NULL,
    is_honors BOOLEAN NOT NULL DEFAULT FALSE,

    course_section_status_id BIGINT NOT NULL,
    delivery_mode_id BIGINT NOT NULL,
    grading_basis_id BIGINT NOT NULL,

    credits DECIMAL(4,2) NOT NULL,
    capacity INT NOT NULL DEFAULT 0,
    hard_capacity INT NULL,
    waitlist_allowed BOOLEAN NOT NULL DEFAULT FALSE,

    start_date DATE NULL,
    end_date DATE NULL,

    parent_section_id BIGINT NULL,
    linked_group_code VARCHAR(50) NULL,
    notes VARCHAR(500) NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_course_section_offering_sub_term
        FOREIGN KEY (course_offering_id, sub_term_id)
            REFERENCES course_offering_sub_term(course_offering_id, sub_term_id),

    CONSTRAINT fk_course_section_status
        FOREIGN KEY (course_section_status_id)
            REFERENCES course_section_status(course_section_status_id),

    CONSTRAINT fk_course_section_academic_division
        FOREIGN KEY (academic_division_id) REFERENCES academic_division(academic_division_id),

    CONSTRAINT fk_course_section_delivery_mode
        FOREIGN KEY (delivery_mode_id) REFERENCES delivery_mode(delivery_mode_id),

    CONSTRAINT fk_course_section_grading_basis
        FOREIGN KEY (grading_basis_id) REFERENCES grading_basis(grading_basis_id),

    CONSTRAINT fk_course_section_parent
        FOREIGN KEY (parent_section_id) REFERENCES course_section(section_id),

    CONSTRAINT uq_course_section_offering_sub_term_letter
        UNIQUE (course_offering_id, sub_term_id, section_letter, is_honors),

    CONSTRAINT chk_course_section_credits
        CHECK (credits >= 0),

    CONSTRAINT chk_course_section_capacity
        CHECK (capacity >= 0),

    CONSTRAINT chk_course_section_hard_capacity
        CHECK (hard_capacity IS NULL OR hard_capacity >= capacity),

    CONSTRAINT chk_course_section_date_range
        CHECK (start_date IS NULL OR end_date IS NULL OR start_date <= end_date)
);

CREATE TABLE course_section_instructor (
    section_instructor_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL,
    staff_id BIGINT NOT NULL,
    section_instructor_role_id BIGINT NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    assignment_start_date DATE NULL,
    assignment_end_date DATE NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_course_section_instructor_section
        FOREIGN KEY (section_id)
            REFERENCES course_section(section_id) ON DELETE CASCADE,

    CONSTRAINT fk_course_section_instructor_staff
        FOREIGN KEY (staff_id) REFERENCES staff(id),

    CONSTRAINT fk_course_section_instructor_role
        FOREIGN KEY (section_instructor_role_id)
            REFERENCES section_instructor_role(section_instructor_role_id),

    CONSTRAINT uq_course_section_instructor_unique
        UNIQUE (section_id, staff_id, section_instructor_role_id),

    CONSTRAINT chk_course_section_instructor_date_range
        CHECK (
            assignment_start_date IS NULL
            OR assignment_end_date IS NULL
            OR assignment_start_date <= assignment_end_date
        )
);

CREATE UNIQUE INDEX uq_course_section_instructor_primary
    ON course_section_instructor (section_id)
    WHERE is_primary = TRUE;

CREATE TABLE course_section_meeting (
    section_meeting_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id BIGINT NOT NULL,
    section_meeting_type_id BIGINT NOT NULL,

    day_of_week SMALLINT NULL,
    start_time TIME NULL,
    end_time TIME NULL,

    building VARCHAR(100) NULL,
    room VARCHAR(50) NULL,

    start_date DATE NULL,
    end_date DATE NULL,

    sequence_number INT NOT NULL DEFAULT 1,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_course_section_meeting_section
        FOREIGN KEY (section_id)
            REFERENCES course_section(section_id) ON DELETE CASCADE,

    CONSTRAINT fk_course_section_meeting_type
        FOREIGN KEY (section_meeting_type_id)
            REFERENCES section_meeting_type(section_meeting_type_id),

    CONSTRAINT chk_course_section_meeting_day_of_week
        CHECK (day_of_week IS NULL OR day_of_week BETWEEN 1 AND 7),

    CONSTRAINT chk_course_section_meeting_time_range
        CHECK (
            start_time IS NULL
            OR end_time IS NULL
            OR start_time < end_time
        ),

    CONSTRAINT chk_course_section_meeting_date_range
        CHECK (
            start_date IS NULL
            OR end_date IS NULL
            OR start_date <= end_date
        ),

    CONSTRAINT uq_course_section_meeting_sequence
        UNIQUE (section_id, sequence_number)
);

CREATE TABLE student_section_enrollment (
    student_section_enrollment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    section_id BIGINT NOT NULL,
    student_section_enrollment_status_id BIGINT NOT NULL,
    grading_basis_id BIGINT NOT NULL,

    enrollment_date DATE NOT NULL DEFAULT CURRENT_DATE,
    registered_at TIMESTAMP NULL,
    waitlisted_at TIMESTAMP NULL,
    drop_date DATE NULL,
    withdraw_date DATE NULL,
    status_changed_at TIMESTAMP NULL,
    status_changed_by_user_id BIGINT NULL,

    credits_attempted DECIMAL(4,2) NULL,
    credits_earned DECIMAL(4,2) NULL,
    waitlist_position INT NULL,

    include_in_gpa BOOLEAN NOT NULL DEFAULT TRUE,
    repeat_code VARCHAR(30) NULL,
    capacity_override BOOLEAN NOT NULL DEFAULT FALSE,
    manual_add_reason VARCHAR(500) NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_student_section_enrollment_student
        FOREIGN KEY (student_id) REFERENCES student(student_id),

    CONSTRAINT fk_student_section_enrollment_section
        FOREIGN KEY (section_id) REFERENCES course_section(section_id),

    CONSTRAINT fk_student_section_enrollment_status
        FOREIGN KEY (student_section_enrollment_status_id)
            REFERENCES student_section_enrollment_status(student_section_enrollment_status_id),

    CONSTRAINT fk_student_section_enrollment_grading_basis
        FOREIGN KEY (grading_basis_id) REFERENCES grading_basis(grading_basis_id),

    CONSTRAINT fk_student_section_enrollment_status_changed_by
        FOREIGN KEY (status_changed_by_user_id) REFERENCES users(id),

    CONSTRAINT uq_student_section_enrollment_student_section
        UNIQUE (student_id, section_id),

    CONSTRAINT chk_student_section_enrollment_drop_date
        CHECK (drop_date IS NULL OR drop_date >= enrollment_date),

    CONSTRAINT chk_student_section_enrollment_withdraw_date
        CHECK (withdraw_date IS NULL OR withdraw_date >= enrollment_date),

    CONSTRAINT chk_student_section_enrollment_drop_withdraw_exclusive
        CHECK (drop_date IS NULL OR withdraw_date IS NULL),

    CONSTRAINT chk_student_section_enrollment_credits_attempted
        CHECK (credits_attempted IS NULL OR credits_attempted >= 0),

    CONSTRAINT chk_student_section_enrollment_credits_earned
        CHECK (credits_earned IS NULL OR credits_earned >= 0),

    CONSTRAINT chk_student_section_enrollment_credits_consistency
        CHECK (
            credits_attempted IS NULL
            OR credits_earned IS NULL
            OR credits_earned <= credits_attempted
        ),

    CONSTRAINT chk_student_section_enrollment_waitlist_position
        CHECK (waitlist_position IS NULL OR waitlist_position > 0)
);

CREATE TABLE student_section_grade (
    student_section_grade_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_section_enrollment_id BIGINT NOT NULL,
    student_section_grade_type_id BIGINT NOT NULL,
    grade_mark_id BIGINT NOT NULL,
    posted_by_user_id BIGINT NULL,
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    posted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_student_section_grade_enrollment
        FOREIGN KEY (student_section_enrollment_id)
            REFERENCES student_section_enrollment(student_section_enrollment_id) ON DELETE CASCADE,

    CONSTRAINT fk_student_section_grade_type
        FOREIGN KEY (student_section_grade_type_id)
            REFERENCES student_section_grade_type(student_section_grade_type_id),

    CONSTRAINT fk_student_section_grade_mark
        FOREIGN KEY (grade_mark_id) REFERENCES grade_mark(grade_mark_id),

    CONSTRAINT fk_student_section_grade_posted_by
        FOREIGN KEY (posted_by_user_id) REFERENCES users(id)
);

CREATE TABLE student_section_enrollment_event (
    student_section_enrollment_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_section_enrollment_id BIGINT NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    from_student_section_enrollment_status_id BIGINT NULL,
    to_student_section_enrollment_status_id BIGINT NULL,
    actor_user_id BIGINT NULL,
    reason VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_student_section_enrollment_event_enrollment
        FOREIGN KEY (student_section_enrollment_id)
            REFERENCES student_section_enrollment(student_section_enrollment_id) ON DELETE CASCADE,

    CONSTRAINT fk_student_section_enrollment_event_from_status
        FOREIGN KEY (from_student_section_enrollment_status_id)
            REFERENCES student_section_enrollment_status(student_section_enrollment_status_id),

    CONSTRAINT fk_student_section_enrollment_event_to_status
        FOREIGN KEY (to_student_section_enrollment_status_id)
            REFERENCES student_section_enrollment_status(student_section_enrollment_status_id),

    CONSTRAINT fk_student_section_enrollment_event_actor
        FOREIGN KEY (actor_user_id) REFERENCES users(id)
);

CREATE INDEX idx_course_section_offering_sub_term
    ON course_section (course_offering_id, sub_term_id);

CREATE INDEX idx_course_section_status
    ON course_section (course_section_status_id);

CREATE INDEX idx_course_section_division
    ON course_section (academic_division_id);

CREATE INDEX idx_course_section_dates
    ON course_section (start_date, end_date);

CREATE INDEX idx_course_section_instructor_staff
    ON course_section_instructor (staff_id);

CREATE INDEX idx_course_section_meeting_section
    ON course_section_meeting (section_id);

CREATE INDEX idx_student_section_enrollment_student
    ON student_section_enrollment (student_id);

CREATE INDEX idx_student_section_enrollment_section
    ON student_section_enrollment (section_id);

CREATE INDEX idx_student_section_enrollment_status
    ON student_section_enrollment (student_section_enrollment_status_id);

CREATE INDEX idx_student_section_enrollment_waitlist
    ON student_section_enrollment (section_id, waitlist_position)
    WHERE waitlist_position IS NOT NULL;

CREATE INDEX idx_student_section_grade_enrollment
    ON student_section_grade (student_section_enrollment_id);

CREATE INDEX idx_student_section_grade_type
    ON student_section_grade (student_section_grade_type_id);

CREATE INDEX idx_student_section_grade_mark
    ON student_section_grade (grade_mark_id);

CREATE INDEX idx_student_section_grade_posted_by
    ON student_section_grade (posted_by_user_id);

CREATE UNIQUE INDEX uq_student_section_grade_current
    ON student_section_grade (student_section_enrollment_id, student_section_grade_type_id)
    WHERE is_current = TRUE;

CREATE INDEX idx_student_section_enrollment_event_enrollment
    ON student_section_enrollment_event (student_section_enrollment_id);

CREATE INDEX idx_student_section_enrollment_event_actor
    ON student_section_enrollment_event (actor_user_id);

CREATE INDEX idx_student_section_enrollment_event_type
    ON student_section_enrollment_event (event_type);

CREATE TRIGGER trg_course_section_updated_at
    BEFORE UPDATE ON course_section
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_course_section_instructor_updated_at
    BEFORE UPDATE ON course_section_instructor
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_course_section_meeting_updated_at
    BEFORE UPDATE ON course_section_meeting
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_student_section_enrollment_updated_at
    BEFORE UPDATE ON student_section_enrollment
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_student_section_grade_updated_at
    BEFORE UPDATE ON student_section_grade
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
