CREATE TABLE transfer_institution (
    transfer_institution_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_transfer_institution_code UNIQUE (code)
);

CREATE TABLE student_transfer_credit (
    student_transfer_credit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL,
    transfer_institution_id BIGINT NOT NULL,

    external_term_label VARCHAR(100) NOT NULL,
    transcript_sort_date DATE NOT NULL,

    external_subject_code VARCHAR(20) NOT NULL,
    external_course_number VARCHAR(20) NOT NULL,
    external_course_title VARCHAR(255) NOT NULL,

    local_subject_code VARCHAR(20) NULL,
    local_course_number VARCHAR(20) NULL,
    local_course_title VARCHAR(255) NULL,

    transfer_grade_mark VARCHAR(20) NOT NULL DEFAULT 'P',
    credits_attempted DECIMAL(5,2) NOT NULL,
    credits_earned DECIMAL(5,2) NOT NULL,
    gpa_credits DECIMAL(5,2) NOT NULL DEFAULT 0,
    quality_points DECIMAL(7,2) NOT NULL DEFAULT 0,
    include_in_gpa BOOLEAN NOT NULL DEFAULT FALSE,

    posted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    notes VARCHAR(500) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_student_transfer_credit_student
        FOREIGN KEY (student_id) REFERENCES student(student_id) ON DELETE CASCADE,

    CONSTRAINT fk_student_transfer_credit_institution
        FOREIGN KEY (transfer_institution_id)
            REFERENCES transfer_institution(transfer_institution_id),

    CONSTRAINT uq_student_transfer_credit_course
        UNIQUE (
            student_id,
            transfer_institution_id,
            external_term_label,
            external_subject_code,
            external_course_number
        ),

    CONSTRAINT chk_student_transfer_credit_attempted
        CHECK (credits_attempted >= 0),

    CONSTRAINT chk_student_transfer_credit_earned
        CHECK (credits_earned >= 0),

    CONSTRAINT chk_student_transfer_credit_gpa_credits
        CHECK (gpa_credits >= 0),

    CONSTRAINT chk_student_transfer_credit_quality_points
        CHECK (quality_points >= 0),

    CONSTRAINT chk_student_transfer_credit_earned_consistency
        CHECK (credits_earned <= credits_attempted),

    CONSTRAINT chk_student_transfer_credit_grade_mark
        CHECK (transfer_grade_mark IN ('P', 'F'))
);

CREATE INDEX idx_student_transfer_credit_student
    ON student_transfer_credit (student_id);

CREATE INDEX idx_student_transfer_credit_institution
    ON student_transfer_credit (transfer_institution_id);

CREATE INDEX idx_student_transfer_credit_sort
    ON student_transfer_credit (student_id, transcript_sort_date);

CREATE TRIGGER trg_transfer_institution_updated_at
    BEFORE UPDATE ON transfer_institution
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();

CREATE TRIGGER trg_student_transfer_credit_updated_at
    BEFORE UPDATE ON student_transfer_credit
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at_timestamp();
